#!/usr/bin/env python3
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("--newpipe", required=True)
parser.add_argument("--extractor", required=True)
args = parser.parse_args()

print(f"Applying patches to {args.newpipe} and {args.extractor}")

def patch(target, old_str, new_str):
    with open(target, "r", encoding="utf-8") as f:
        patch_content = f.read()
    patch_content = patch_content.replace(old_str, new_str)
    with open(target, "w", encoding="utf-8") as f:
        f.write(patch_content)

# ================================================================

local_patch_str = """
includeBuild("../NewPipeExtractor") {
    dependencySubstitution {
        substitute(module("com.github.TeamNewPipe:NewPipeExtractor"))
            .using(project(":extractor"))
    }
}
"""
newpipe_settings_path = f"{args.newpipe}/settings.gradle.kts"
with open(newpipe_settings_path, "a", encoding="utf-8") as f:
    f.write("\n" + local_patch_str)

# ================================================================

my_json_url = (
    "https://github.com/6p6h/np_build_with_at_test/releases/latest/download/latest.json"
)
newpipe_update_path = (
    f"{args.newpipe}/app/src/main/java/org/schabi/newpipe/NewVersionWorker.kt"
)
patch(newpipe_update_path, "https://newpipe.net/api/data.json", my_json_url)

# ================================================================

target_str = """
                        .setAutoGenerated(isAutoGenerated)
                        .build());
"""
patch_str = """
                        .setAutoGenerated(isAutoGenerated)
                        .build());
                subtitlesToReturn.add(new SubtitlesStream.Builder()
                        .setContent(cleanUrl.replaceAll("&hl=[^&]*", "") + "&fmt=" + format.getSuffix() + "&tlang=zh-Hans", true)
                        .setMediaFormat(format)
                        .setLanguageCode("zh-Hans")
                        .setAutoGenerated(isAutoGenerated)
                        .build());
"""

target_str2 = """
        final JsonArray captionsArray = playerCaptionsTracklistRenderer.getArray("captionTracks");
"""
patch_str2 = """
        final JsonArray captionsArray = playerCaptionsTracklistRenderer.getArray("captionTracks");
        final JsonArray audiosArray = playerCaptionsTracklistRenderer.getArray("audioTracks");
        final JsonArray translationsArray = playerCaptionsTracklistRenderer.getArray("translationLanguages");
        System.out.println("captionTracks = " + captionsArray);
        System.out.println("audioTracks = " + audiosArray);
        System.out.println("translationLanguages = " + translationsArray);
"""
extractor_path = (
    f"{args.extractor}/extractor/src/main/java/"
    "org/schabi/newpipe/extractor/services/youtube/extractors/"
    "YoutubeStreamExtractor.java"
)
patch(extractor_path, target_str, patch_str)
patch(extractor_path, target_str2, patch_str2)

# ================================================================

req_str = """
                   final boolean automaticLocalizationHeader) {
"""
req_patch_str = """
                   final boolean automaticLocalizationHeader) {
        System.out.println("=== Request Built ===");
        System.out.println("Method: " + httpMethod);
        System.out.println("URL: " + url);
        System.out.println("Headers: " + headers);
        System.out.println("Localization: " + localization);
        System.out.println("AutoLocalizationHeader: " + automaticLocalizationHeader);
        System.out.println("=====================");

"""
req_path = (
    f"{args.extractor}/extractor/src/main/java/"
    "org/schabi/newpipe/extractor/downloader/Request.java"
)
patch(req_path, req_str, req_patch_str)

# ================================================================

print("file patch finished!")
